// Package state implements the on-disk layout, box metadata, and locking.
package state

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"
)

// Dir returns $XDG_STATE_HOME/agentbox (or ~/.local/state/agentbox).
func Dir() string {
	if x := os.Getenv("XDG_STATE_HOME"); x != "" {
		return filepath.Join(x, "agentbox")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "state", "agentbox")
}

// CacheDir returns $XDG_CACHE_HOME/agentbox.
func CacheDir() string {
	if x := os.Getenv("XDG_CACHE_HOME"); x != "" {
		return filepath.Join(x, "agentbox")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".cache", "agentbox")
}

// BoxMeta is boxes/<key>/meta.json: everything frozen at creation, recomputed
// and compared on every subsequent invocation so that configuration drift is
// noticed rather than silently applied to a box that predates it.
//
// One box per workspace root means this is also the project record; there is
// no second level of identity and no instance name.
type BoxMeta struct {
	Key               string `json:"key"`
	WorkspaceRealpath string `json:"workspace_realpath"`
	Slug              string `json:"slug"`
	Backend           string `json:"backend"`
	Tier              string `json:"tier"`
	ConfigDigest      string `json:"config_digest"`
	ImageRef          string `json:"image_ref"`
	// ImageBuilt records that agentbox built this image rather than being
	// pointed at one. `rm` reclaims only what agentbox made: deleting a
	// pinned [image].ref would take out an image the user owns, and quite
	// possibly one other things on the host depend on.
	ImageBuilt     bool      `json:"image_built"`
	MaskDigest     string    `json:"mask_digest"`
	MaskMode       string    `json:"mask_mode"`
	ForceIsolation string    `json:"force_isolation,omitempty"` // recorded and surfaced
	MemoryLimit    string    `json:"memory_limit"`
	CreatedAt      time.Time `json:"created_at"`
	LastExecAt     time.Time `json:"last_exec_at"`
	// VMTierNoticed records that the one-time notice about auto-selecting the
	// vm tier has been shown for this workspace.
	VMTierNoticed bool `json:"vm_tier_noticed,omitempty"`
}

// Store wraps the state directory root (injectable for tests).
type Store struct{ Root string }

func Open(root string) *Store {
	if root == "" {
		root = Dir()
	}
	return &Store{Root: root}
}

func (s *Store) BoxDir(key string) string { return filepath.Join(s.Root, "boxes", key) }

func (s *Store) LoadBox(key string) (*BoxMeta, error) {
	var m BoxMeta
	if err := readJSON(filepath.Join(s.BoxDir(key), "meta.json"), &m); err != nil {
		return nil, err
	}
	return &m, nil
}

func (s *Store) SaveBox(m *BoxMeta) error {
	dir := s.BoxDir(m.Key)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	return writeJSON(filepath.Join(dir, "meta.json"), m)
}

// BoxExists reports whether a box record exists for this workspace.
func (s *Store) BoxExists(key string) bool {
	_, err := os.Stat(filepath.Join(s.BoxDir(key), "meta.json"))
	return err == nil
}

// ListBoxes enumerates every box agentbox knows about, ordered by creation
// time. Used only for teardown and diagnostics; addressing a box is done by
// standing in its workspace.
func (s *Store) ListBoxes() ([]*BoxMeta, error) {
	ents, err := os.ReadDir(filepath.Join(s.Root, "boxes"))
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var boxes []*BoxMeta
	for _, e := range ents {
		if !e.IsDir() {
			continue
		}
		if m, err := s.LoadBox(e.Name()); err == nil {
			boxes = append(boxes, m)
		}
	}
	sort.Slice(boxes, func(i, j int) bool {
		if boxes[i].CreatedAt.Equal(boxes[j].CreatedAt) {
			return boxes[i].Key < boxes[j].Key
		}
		return boxes[i].CreatedAt.Before(boxes[j].CreatedAt)
	})
	return boxes, nil
}

func (s *Store) RemoveBox(key string) error {
	return os.RemoveAll(s.BoxDir(key))
}

// GeneratedFileHeader builds the header generated files carry, naming
// the tool, version, and source config, and are safe to delete.
func GeneratedFileHeader(version, sourceConfig string) string {
	return fmt.Sprintf("# generated by agentbox %s from %s\n# safe to delete: reconstructible from configuration and workspace state\n", version, sourceConfig)
}

func readJSON(path string, v any) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, v)
}

func writeJSON(path string, v any) error {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, append(data, '\n'), 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// WriteJSONFile is the exported form for generated artifacts (masks.json,
// spec.json).
func WriteJSONFile(path string, v any) error { return writeJSON(path, v) }
